version: "2"
services:

  camunda-platform-server:
    image: lwluc/camunda-platform-server
    container_name: camunda-platform-server
    mem_limit: 512M
    ports:
      - 8080:8080

  camunda-platform-client:
    image: lwluc/camunda-platform-client
    container_name: camunda-platform-client
    mem_limit: 512M
    depends_on:
      - camunda-platform-server
  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.2
    container_name: elasticsearch
    ports:
      - 9200:9200
    volumes:
      - ./elasticsearchData:/usr/share/elasticsearch/data
    environment:
      - node.name=elasticsearch
      - discovery.type=single-node
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - xpack.license.self_generated.type=${LICENSE}
    mem_limit: ${MEM_LIMIT}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s --cacert config/certs/ca/ca.crt https://localhost:9200 | grep -q 'missing authentication credentials'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120

  camunda-optimize:
    image: registry.camunda.cloud/optimize-ee/optimize:3.10.5
    mem_limit: 512M
    environment:
      - OPTIMIZE_CAMUNDABPM_REST_URL=http://camunda-platform-server:8080/engine-rest
      - OPTIMIZE_ELASTICSEARCH_HOST=elasticsearch
      - OPTIMIZE_ELASTICSEARCH_HTTP_PORT=9200
      - OPTIMIZE_ES_SECURITY_USERNAME="elastic"
      - OPTIMIZE_ES_SECURITY_PASSWORD=${ELASTIC_PASSWORD}
      - OPTIMIZE_EVENT_BASED_PROCESSES_IMPORT_ENABLED=true
      - OPTIMIZE_CAMUNDA_BPM_EVENT_IMPORT_ENABLED=true
      - OPTIMIZE_EVENT_INGESTION_ACCESS_TOKEN=demo
      - OPTIMIZE_EVENT_BASED_PROCESSES_USER_IDS=[admin]
    depends_on:
      - camunda-platform-server
      - elasticsearch
    volumes:
      - ./licenses/OptimizeLicense.txt:/optimize/config/OptimizeLicense.txt:ro
    restart: always
    ports:
      - 8090:8090
      - 8091:8091
