services:
  camunda-platform-server:
    image: lwluc/camunda-platform-server
    container_name: camunda-platform-server
    ports:
      - "8080:8080"

  camunda-platform-client:
    image: lwluc/camunda-platform-client
    container_name: camunda-platform-client
    environment:
      - MICRONAUT_ENVIRONMENTS=docker
    depends_on:
      - camunda-platform-server

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    container_name: elasticsearch
    ports:
      - "9200:9200"
    volumes:
      - ./elasticsearchData:/usr/share/elasticsearch/data
    environment:
      - node.name=elasticsearch
      - discovery.type=single-node
      - ELASTIC_PASSWORD=password
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - xpack.license.self_generated.type=basic
    mem_limit: 1073741824
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s --cacert config/certs/ca/ca.crt https://localhost:9200 | grep -q 'missing authentication credentials'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120

  camunda-optimize:
    image: registry.camunda.cloud/optimize-ee/optimize:3.15.0
    environment:
      - ABSOLUTE_PATH_ON_HOST_TO_CONFIGURATION_FILE:/optimize/config/environment-config.yaml:ro
    depends_on:
      - camunda-platform-server
      - elasticsearch
    volumes:
      - ./optimize-environment-config.yaml:/optimize/config/environment-config.yaml
      - ./licenses/OptimizeLicense.txt:/optimize/config/OptimizeLicense.txt:ro
    restart: always
    ports:
      - "8090:8090"
      - "8091:8091"
