version: "2"
services:
  camunda-platform-server:
    image: lwluc/camunda-platform-server
    container_name: camunda-platform-server
    mem_limit: 512M
    ports:
      - 8080:8080

  camunda-platform-client:
    image: lwluc/camunda-platform-client
    container_name: camunda-platform-client
    mem_limit: 512M
    depends_on:
      - camunda-platform-server
  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.10
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
    restart: always
    mem_limit: 2g

  camunda-optimize:
    image: registry.camunda.cloud/optimize-ee/optimize:3.11.0-RC3
    mem_limit: 512M
    environment:
      - OPTIMIZE_CAMUNDABPM_REST_URL=http://camunda-platform-server:8080/engine-rest
      - OPTIMIZE_ELASTICSEARCH_HOST=elasticsearch
      - OPTIMIZE_ELASTICSEARCH_HTTP_PORT=9200
      - OPTIMIZE_EVENT_BASED_PROCESSES_IMPORT_ENABLED=true
      - OPTIMIZE_CAMUNDA_BPM_EVENT_IMPORT_ENABLED=true
      - OPTIMIZE_EVENT_INGESTION_ACCESS_TOKEN=demo
      - OPTIMIZE_EVENT_BASED_PROCESSES_USER_IDS=[admin]
    depends_on:
      - camunda-platform-server
      - elasticsearch
    volumes:
      - ./licenses/OptimizeLicense.txt:/optimize/config/OptimizeLicense.txt:ro
    restart: always
    ports:
      - 8090:8090
      - 8091:8091
