security:
  auth:
    superUserIds: [admin]

api:
  accessToken: demo

engines:
  "camunda-platform-server":
    name: default
    rest: "http://camunda-platform-server:8080/engine-rest"
    importEnabled: true
    eventImportEnabled: false
    authentication:
      enabled: false
    webapps:
      enabled: false

es:
  connection:
    nodes:
    - host: elasticsearch
      httpPort: 9200
  security:
    username: elastic
    password: password

eventBasedProcess:
  authorizedUserIds: [admin]
  eventImport:
    enabled: true