kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: elasticsearch-persistent
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
spec:
  ports:
    - port: 9200
  selector:
    app: elasticsearch
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      initContainers:
      - name: set-vm-max-map-count
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ['sysctl', '-w', 'vm.max_map_count=262144']
        securityContext:
          privileged: true
      containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:8.6.2
        imagePullPolicy: IfNotPresent
        env:
        - name: node.name
          value: es01
        - name: discovery.type
          value: single-node
        - name: ELASTIC_PASSWORD
          value: password
        - name: bootstrap.memory_lock
          value: "true"
        - name: xpack.security.enabled
          value: "false"
        - name: xpack.security.http.ssl.enabled
          value: "false"
        - name: xpack.security.transport.ssl.enabled
          value: "false"
        - name: xpack.license.self_generated.type
          value: basic
        ports:
          - containerPort: 9200
        resources:
          requests:
            memory: "1.5Gi"
          limits:
            memory: "1.5Gi"
        livenessProbe:
          httpGet:
            path: /_cluster/health
            port: 9200
          initialDelaySeconds: 5
          periodSeconds: 3
        startupProbe:
          httpGet:
            path: /_cluster/health
            port: 9200
          initialDelaySeconds: 5
          failureThreshold: 4
          periodSeconds: 10
      restartPolicy: Always
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: elasticsearch-persistent