micronaut:
  server:
    port: 8081
  application:
    name: camunda-platform-client
camunda.external-client:
  base-url: http://localhost:8080/engine-rest
  max-tasks: 1
netty:
  default:
    allocator:
      max-order: 3
