apiVersion: v1
kind: Service
metadata:
  name: camunda-platform-server
  labels:
    app: camunda-platform-server
spec:
  ports:
    - port: 8080
  selector:
    app: camunda-platform-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: camunda-platform-server
  labels:
    app: camunda-platform-server
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: camunda-platform-server
  template:
    metadata:
      labels:
        app: camunda-platform-server
    spec:
      containers:
        - image: lwluc/camunda-platform-server
          name: camunda-platform-server
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "536870912"
          livenessProbe:
            httpGet:
              path: /engine-rest/engine
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 3
          startupProbe:
            httpGet:
              path: /engine-rest/engine
              port: 8080
            initialDelaySeconds: 10
            failureThreshold: 5
            periodSeconds: 5
      restartPolicy: Always
