name: Java CI
on:
  push:
    branches:
      - main
      - 'releases/**'
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: camunda-platform-client
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/.m2/repository
          key: ${{ runner.os }}-gradle-test-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-test-
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build And Push Docker Image (Server)
        env:
          DOCKER_REPOSITORY_PATH: ${{ secrets.DOCKER_REPOSITORY_PATH }}
          TESTCONTAINERS_RYUK_DISABLED: true
        run: |
          export DOCKER_IMAGE=`echo "${DOCKER_REPOSITORY_PATH}/camunda-platform-client" | sed -e 's#//#/#' -e 's#^/##'`
          ./gradlew bootBuildImage --imageName=lwluc/camunda-platform-client
